// private int status;
// private String name;
// private String code;
// private String message;

// required: associates our `main.dart` with the code generated by Freezed
import 'package:freezed_annotation/freezed_annotation.dart';

part 'error_response.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'error_response.g.dart';

@freezed
class ErrorResponse with _$ErrorResponse {
  const factory ErrorResponse({required int status, required String message}) =
      _ErrorResponse;

  factory ErrorResponse.fromJson(Map<String, Object?> json) =>
      _$ErrorResponseFromJson(json);
}
